# AutoPunkte Configuration

# List of merchants for which to activate coupons
merchants:
  - name: Dell
    partner_id: lp475351
  - name: Douglas
    partner_id: lp703660
  - name: Edeka
    partner_id: lp747

  # Add more merchants as needed
  # Partner IDs can be found in the URL when selecting a merchant on the Payback website
  # For example, https://www.payback.de/coupons?partnerId=lp732 for Decathlon

# Configuration options
options:
  notify_on_success: true
  notify_on_failure: true
  activation_timeout: 30 # seconds
