name: Activate Payback Coupons

on:
  schedule:
    # Run every Monday and Thursday at 00:00 UTC
    - cron: "0 0 * * 1,4"
  workflow_dispatch:

jobs:
  activate:
    name: Activate Coupons
    runs-on: macos-latest
    timeout-minutes: 15 # Prevent hung jobs

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate secrets
        env:
          PAYBACK_USERNAME: ${{ secrets.PAYBACK_USERNAME }}
          PAYBACK_PASSWORD: ${{ secrets.PAYBACK_PASSWORD }}
        run: |
          if [ -z "$PAYBACK_USERNAME" ] || [ -z "$PAYBACK_PASSWORD" ]; then
            echo "::error::Missing required secrets. Please set PAYBACK_USERNAME and PAYBACK_PASSWORD in your repository secrets."
            exit 1
          fi

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Setup for Chrome and debugging
        run: |
          # Use pre-installed Chrome and ChromeDriver
          echo "Using pre-installed Chrome: $(google-chrome --version)"
          echo "Using pre-installed ChromeDriver: $(chromedriver --version)"
          echo "ChromeDriver path: $CHROMEWEBDRIVER"

          # Install xquartz for display support
          brew install --cask xquartz

          # Create debug directory
          mkdir -p debug_info

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          uv sync

      - name: Activate Payback coupons
        id: activate
        env:
          PAYBACK_USERNAME: ${{ secrets.PAYBACK_USERNAME }}
          PAYBACK_PASSWORD: ${{ secrets.PAYBACK_PASSWORD }}
          GITHUB_ACTIONS: "true" # Explicitly set for script detection
          PYTHONUNBUFFERED: "1" # Ensure Python output is not buffered
          DEBUG: "1" # Enable additional debugging
          CHROME_PATH: "/usr/bin/google-chrome" # Use pre-installed Chrome
        run: |
          # Start virtual display for macOS
          defaults write org.x.X11 app_to_run /usr/bin/true
          open -a XQuartz
          sleep 5

          # Collect system info for debugging
          echo "System info:" > debug_info/system_info.txt
          uname -a >> debug_info/system_info.txt
          sw_vers >> debug_info/system_info.txt
          echo "Chrome info:" >> debug_info/system_info.txt
          google-chrome --version >> debug_info/system_info.txt

          # Run the activation script with more verbose output
          uv run activate.py --log-level DEBUG

      - name: Upload activation logs
        if: always() # Run even if previous steps failed
        uses: actions/upload-artifact@v4
        with:
          name: activation-logs
          path: |
            payback_activation_*.log
            autopunkte.log
            activation_results_*.json
            debug_info/*
          retention-days: 7

      - name: Upload screenshots and HTML
        if: always() # Always upload screenshots to help with debugging
        uses: actions/upload-artifact@v4
        with:
          name: activation-results
          path: |
            payback_coupons_*.png
            payback_coupons_*.html
          retention-days: 7

      - name: Send notification on failure
        if: failure()
        run: |
          echo "Payback coupon activation workflow failed. Check the logs for details."
          # You could add additional notification methods here (email, Slack, etc.)
