name: Activate Payback Coupons

"on":
  schedule:
    # Run every Monday and Thursday at 10:00 AM UTC
    - cron: "0 10 * * 1,4"
  workflow_dispatch:

jobs:
  activate:
    name: Activate Coupons
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb x11-utils x11-xserver-utils libxss1

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          uv sync

      - name: Activate Payback coupons
        env:
          PAYBACK_USERNAME: ${{ secrets.PAYBACK_USERNAME }}
          PAYBACK_PASSWORD: ${{ secrets.PAYBACK_PASSWORD }}
          DISPLAY: ":99.0"
          GITHUB_ACTIONS: "true"
        run: |
          # Start virtual display with larger resolution and color depth
          Xvfb :99 -screen 0 1920x1080x24 -ac +extension GLX +render -noreset > /dev/null 2>&1 &
          # Wait for Xvfb to start
          sleep 5
          # Check if display is working
          xdpyinfo -display :99 > /dev/null || (echo "Xvfb failed to start" && exit 1)
          # Run without headless flag
          uv run activate.py

      - name: Upload activation logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: activation-logs
          path: |
            payback_activation_*.log
            autopunkte.log
            activation_results_*.json
          retention-days: 7

      - name: Upload screenshots and HTML
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: activation-results
          path: |
            payback_coupons_*.png
            payback_coupons_*.html
          retention-days: 7
